package com.depli.service.store.graph.impl;

import com.depli.service.store.cache.graph.ClassLoadingGraphDataCacheService;
import com.depli.service.store.graph.ClassLoadingGraphDataService;
import com.depli.store.cache.graph.ClassLoadingGraphData;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;

/**
 * Class loading graph data service implementation
 *
 * @author lpsandaruwan
 * @since 9/23/17
 */

@Service
public class ClassLoadingGraphDataServiceImpl implements ClassLoadingGraphDataService {

  @Autowired
  private ClassLoadingGraphDataCacheService classLoadingGraphDataCacheService;

  @Override
  public ClassLoadingGraphData getByNodeId(Long nodeId) {
    return classLoadingGraphDataCacheService.getCache().get(nodeId);
  }

  /**
   * Stores ClassLoadingGraphDataService in class loading graph data object cache
   * using Long value, nodeId which is generated by application when persisting JMX remote
   * connection node's metadata.
   *
   * @param nodeId node ID of the JMX remote connection
   * @param classLoadingGraphData Class loading graph data object for particular node ID
   */
  @Override
  public void save(Long nodeId, ClassLoadingGraphData classLoadingGraphData) {
    classLoadingGraphDataCacheService.getCache().put(nodeId, classLoadingGraphData);
  }
}
