package com.depli.service.store.cache.connector;

import com.depli.store.cache.connector.ConnectionTree;
import org.infinispan.Cache;

/**
 * Connection tree cache service
 *
 * Service to retrieve and clear the cache which contains ConnectionTree objects which contain sever connections.
 *
 * @author lpsandaruwan
 * @since 9/17/17
 */

public interface ConnectionTreeCacheService {

    /**
     * Returns infinispan cache which uses to store and retrieve connection tree
     * objects mapped by the Long values, node IDs related to remote JMX connections
     * which are generated by hibernate.
     *
     * @return connection tree object cache
     */
    public Cache<Long, ConnectionTree> getCache();

    /**
     * Clears the cache which contains the map of Long values, node IDs related to
     * remote JMX connections which are generated by hibernate and connection tree
     * objects.
     */
    public void clearCache();
}
