package com.depli.service.store.cache.descriptor;

import com.depli.store.cache.descriptor.OperatingSystemDescriptor;
import org.infinispan.Cache;

/**
 * Operating System descriptor cache service
 * <p>
 * Service to retrieve and clear the cache which contains Operating System descriptors.
 *
 * @author lpsandaruwan
 * @since 9/16/17
 */

public interface OperatingSystemDescriptorCacheService {

  /**
   * Returns infinispan cache which uses to store and retrieve Operating System
   * descriptors mapped by the Long values, node IDs related to remote JMX connections
   * which are generated by hibernate.
   *
   * @return operating system descriptor cache
   */
  public Cache<Long, OperatingSystemDescriptor> getCache();

  /**
   * Clears the cache which contains the map of Long values, node IDs related to
   * remote JMX connections which are generated by hibernate and Operating System
   * descriptors.
   */
  public void clearCache();
}
