package com.depli.service.store.cache.descriptor;

import com.depli.store.cache.descriptor.PlatformResourcesDescriptor;
import org.infinispan.Cache;

/**
 * Platform Resources descriptor cache service
 * <p>
 * Service to retrieve and clear the cache which contains Platform Resources descriptors.
 *
 * @author lpsandaruwan
 * @since 9/16/17
 */

public interface PlatformResourcesDescriptorCacheService {

    /**
     * Returns infinispan cache which uses to store and retrieve Platform Resources
     * descriptors mapped by the Long values, node IDs related to remote JMX connections
     * which are generated by hibernate.
     *
     * @return platform resources descriptor cache
     */
    public Cache<Long, PlatformResourcesDescriptor> getCache();

    /**
     * Clears the cache which contains the map of Long values, node IDs related to
     * remote JMX connections which are generated by hibernate and Platform Resources
     * descriptors.
     */
    public void clearCache();
}
