package com.depli.service.store.cache;

import com.depli.store.cache.descriptor.MemoryUsageDescriptor;
import org.infinispan.Cache;

/**
 * Memory Usage descriptor cache service
 * <p>
 * Service to retrieve and clear the cache which contains memory usage descriptors.
 *
 * @author lpsandaruwan
 * @since 9/16/17
 */

public interface MemoryUsageDescriptorCacheService {

    /**
     * Returns infinispan cache which uses to store and retrieve memory usage
     * descriptors mapped by the Long values, node IDs related to remote JMX connections
     * which are generated by hibernate.
     *
     * @return memory usage descriptor cache
     */
    public Cache<Long, MemoryUsageDescriptor> getCache();

    /**
     * Clears the cache which contains the map of Long values, node IDs related to
     * remote JMX connections which are generated by hibernate and memory usage
     * descriptors.
     */
    public void clearCache();
}
