package com.depli.service.store.cache;

import com.depli.store.cache.descriptor.ThreadDescriptor;
import org.infinispan.Cache;

/**
 * Thread descriptor cache service
 * <p>
 * Service to retrieve and clear the cache which contains thread descriptors.
 *
 * @author lpsandaruwan
 * @since 9/16/17
 */

public interface ThreadDescriptorCacheService {

    /**
     * Returns infinispan cache which uses to store and retrieve Thread
     * descriptors mapped by the Long values, node IDs related to remote JMX connections
     * which are generated by hibernate.
     *
     * @return thread descriptor cache
     */
    public Cache<Long, ThreadDescriptor> getCache();

    /**
     * Clears the cache which contains the map of Long values, node IDs related to
     * remote JMX connections which are generated by hibernate and Thread
     * descriptors.
     */
    public void clearCache();
}
