package com.depli.service.store.descriptor;

import com.depli.store.cache.descriptor.MemoryUsageDescriptor;

/**
 * Memory Usage Descriptor Service
 * <p>
 * Provides service to manage memory usage descriptor cache and to retrieve
 * manipulated data from cache.
 *
 * @author lpsandaruwan
 * @since 9/16/17
 */

public interface MemoryDescriptorService {

    /**
     * Retrieves memory usage descriptor object from memory usage descriptor cache
     * using Long value, nodeId which is generated by application when persisting JMX remote
     * connection node's metadata.
     *
     * @param nodeId node ID of the JMX remote connection
     * @return memory usage descriptor for particular node ID
     */
    public MemoryUsageDescriptor getByNodeId(Long nodeId);

    /**
     * Stores memory usage descriptor object in memory usage descriptor cache
     * using Long value, nodeId which is generated by application when persisting JMX remote
     * connection node's metadata.
     *
     * @param nodeId                node ID of the JMX remote connection
     * @param memoryUsageDescriptor memory usage descriptor for particular node ID
     */
    public void save(Long nodeId, MemoryUsageDescriptor memoryUsageDescriptor);
}
