package com.depli.service.store.descriptor;

import com.depli.store.cache.descriptor.OperatingSystemDescriptor;

/**
 * Operating System Descriptor Service
 * <p>
 * Provides service to manage operating system descriptor cache and to retrieve
 * manipulated data from cache.
 *
 * @author lpsandaruwan
 * @since 9/16/17
 */

public interface OperatingSystemDescriptorService {

    /**
     * Retrieves operating system descriptor object from operating system descriptor cache
     * using Long value, nodeId which is generated by application when persisting JMX remote
     * connection node's metadata.
     *
     * @param nodeId node ID of the JMX remote connection
     * @return operating system descriptor for particular node ID
     */
    public OperatingSystemDescriptor getByNodeId(Long nodeId);

    /**
     * Stores operating system descriptor object in operating system descriptor cache
     * using Long value, nodeId which is generated by application when persisting JMX remote
     * connection node's metadata.
     *
     * @param nodeId                    node ID of the JMX remote connection
     * @param operatingSystemDescriptor operating system descriptor for particular node ID
     */
    public void save(Long nodeId, OperatingSystemDescriptor operatingSystemDescriptor);
}
