package com.depli.service.store.descriptor;

import com.depli.store.cache.descriptor.PlatformResourcesDescriptor;

/**
 * Platform Resources Descriptor Service
 * <p>
 * Provides service to manage platform resources descriptor cache and to retrieve
 * manipulated data from cache.
 *
 * @author lpsandaruwan
 * @since 9/16/17
 */

public interface PlatformResourcesDescriptorService {

    /**
     * Retrieves platform resources descriptor object from platform resources descriptor cache
     * using Long value, nodeId which is generated by application when persisting JMX remote
     * connection node's metadata.
     *
     * @param nodeId node ID of the JMX remote connection
     * @return platform resources descriptor for particular node ID
     */
    public PlatformResourcesDescriptor getByNodeId(Long nodeId);

    /**
     * Stores platform resources descriptor object in platform resources descriptor cache
     * using Long value, nodeId which is generated by application when persisting JMX remote
     * connection node's metadata.
     *
     * @param nodeId                      node ID of the JMX remote connection
     * @param platformResourcesDescriptor platform resources descriptor for particular node ID
     */
    public void save(Long nodeId, PlatformResourcesDescriptor platformResourcesDescriptor);
}
