package com.depli.service.store.descriptor;

import com.depli.store.cache.descriptor.ThreadDescriptor;

/**
 * Thread Descriptor Service
 * <p>
 * Provides service to manage thread descriptor cache and to retrieve
 * manipulated data from cache.
 *
 * @author lpsandaruwan
 * @since 9/16/17
 */

public interface ThreadDescriptorService {

    /**
     * Retrieves thread descriptor object from thread descriptor cache
     * using Long value, nodeId which is generated by application when persisting JMX remote
     * connection node's metadata.
     *
     * @param nodeId node ID of the JMX remote connection
     * @return thread descriptor for particular node ID
     */
    public ThreadDescriptor getByNodeId(Long nodeId);

    /**
     * Stores thread descriptor object in thread descriptor cache
     * using Long value, nodeId which is generated by application when persisting JMX remote
     * connection node's metadata.
     *
     * @param nodeId           node ID of the JMX remote connection
     * @param threadDescriptor thread descriptor for particular node ID
     */
    public void save(Long nodeId, ThreadDescriptor threadDescriptor);
}
