package com.depli.service.store.graph;

import com.depli.store.cache.graph.ClassLoadingGraphData;

/**
 * Class Loading Graph Data Service
 *
 * Provides service to manage class loading data graph cache and to consume
 * manipulated data from cache.
 *
 * @author lpsandaruwan
 * @since 9/23/17
 */

public interface ClassLoadingGraphDataService {

  /**
   * Retrieves thread descriptor object from class loading graph data object cache
   * using Long value, nodeId which is generated by application when persisting JMX remote
   * connection node's metadata.
   *
   * @param nodeId node ID of the JMX remote connection
   * @return class loading graph data object for particular node ID
   */
  public ClassLoadingGraphData getByNodeId(Long nodeId);

  /**
   * Stores ClassLoadingGraphDataService in class loading graph data object cache
   * using Long value, nodeId which is generated by application when persisting JMX remote
   * connection node's metadata.
   *
   * @param nodeId node ID of the JMX remote connection
   * @param classLoadingGraphData Class loading graph data object for particular node ID
   */
  public void save(Long nodeId, ClassLoadingGraphData classLoadingGraphData);
}
