package com.depli.service.store.connector;

import com.depli.store.cache.connector.ConnectionTree;

/**
 * Connection Tree Service
 *
 * Provides service to manage class connection tree object cache and to retrieve
 * manipulated data from cache.
 *
 * @author lpsandaruwan
 * @since 9/17/17
 */

public interface ConnectionTreeService {

  /**
   * Retrieves connection tree object from connection tree object cache using Long value, nodeId
   * which is generated by application when persisting JMX remote connection node's metadata.
   *
   * @param nodeId node ID of the JMX remote connection
   * @return connection tree object for particular node ID
   */
  public ConnectionTree getByNodeId(Long nodeId);

  /**
   * Stores connection tree object in connection tree object cache using Long value, nodeId which is
   * generated by application when persisting JMX remote connection node's metadata.
   *
   * @param nodeId node ID of the JMX remote connection
   * @param connectionTree connection tree object for particular node ID
   */
  public void save(Long nodeId, ConnectionTree connectionTree);
}
