package com.depli.service.store.cache.graph;

import com.depli.service.store.graph.ClassLoadingGraphDataService;
import com.depli.store.cache.graph.ClassLoadingGraphData;
import org.infinispan.Cache;

/**
 * Class loading graph data cache service
 *
 * Service to retrieve and clear the cache which contains class loading graph data objects.
 *
 * @author lpsandaruwan
 * @since 9/23/17
 */

public interface ClassLoadingGraphDataCacheService {

  /**
   * Returns infinispan cache which uses to store and retrieve class loading graph data
   * mapped by the Long values, node IDs related to remote JMX connections which are
   * generated by hibernate.
   *
   * @return Class loading graph data object cache
   */
  public Cache<Long, ClassLoadingGraphData> getCache();

  /**
   * Clears the cache which contains the map of Long values, node IDs related to
   * remote JMX connections which are generated by hibernate and class loading graph data objects.
   */
  public void clearCache();
}
