package com.depli.service.store.cache.graph;

import com.depli.store.cache.graph.ProcessingUnitGraphData;
import org.infinispan.Cache;

/**
 * Processing unit graph data cache service
 *
 * Service to retrieve and clear the cache which contains CPU graph data objects.
 *
 * @author lpsandaruwan
 * @since 9/18/17
 */

public interface ProcessingUnitGraphDataCacheService {

  /**
   * Returns infinispan cache which uses to store and retrieve CPU graph data
   * mapped by the Long values, node IDs related to remote JMX connections which are
   * generated by hibernate.
   *
   * @return CPU graph data object cache
   */
  public Cache<Long, ProcessingUnitGraphData> getCache();

  /**
   * Clears the cache which contains the map of Long values, node IDs related to
   * remote JMX connections which are generated by hibernate and CPU graph data objects.
   */
  public void clearCache();
}
